runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
        target_utilization: 0.9

resources:
    cpu: 1
    memory_gb: 4.6
    disk_size_gb: 10

network:
  name: default